// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npbblbwuoaqcsysrzjiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wYmJsYnd1b2FxY3N5c3J6amlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMzU3OTQsImV4cCI6MjA1MDcxMTc5NH0.d5j3bCX2izoOeMwhXoJwV34qHLcZxnRclPONsQBca-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});